---
version: "3.7"

name: titanic

services:
  app:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    env_file:
      - .env
    container_name: titanic_app
    volumes:
      - .:/src
    ports:
      - 8501:${APP_PORT:-8501}
