---
services:
  # - type: web
  #   name: ml
  #   runtime: docker
  #   region: singapore
  #   plan: standard
  #   branch: main
  #   repo: https://github.com/shivan-eyespace/titanic.git
  #   rootDir: ml
  #   healthCheckPath: /
  - type: web
    name: api
    runtime: docker
    region: singapore
    plan: free
    branch: main
    repo: https://github.com/shivan-eyespace/titanic.git
    rootDir: api
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: titanic_db
          property: connectionString
      - key: CACHE_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
  - type: redis
    name: cache
    plan: free
databases:
  - name: db
